Require GnuTLS when building with QEMU driver
Since "799011b vircrypto: Rely on GnuTLS for hash functions", building
without GnuTLS results in runtime errors:

$ virsh define guest.xml
error: Failed to define domain from guest.xml
error: invalid argument: could not find capabilities for arch=ppc64le

from libvirtd:
error : virCryptoHashBuf:84 : invalid argument: algorithm=1 is not supported
error : virCapabilitiesDomainDataLookupInternal:736 : invalid
argument: could not find capabilities for arch=ppc64le

Signed-off-by: Fabiano Rosas <farosas@linux.ibm.com>